export interface JournalEntry {
  date: string;
  author?: string;
  title?: string;
  titleBorder?: boolean;
  lines: string[];
  footer?: string;
}

export const journalEntries: JournalEntry[] = [
  {
    date: "2022/03/10,",
    title: "Verluste im Krieg",
    lines: [
      "",
      "In Charkiv",
      "vorige Woche",
      "sind vor russischen Bomben",
      "nicht nur Bewohner der Stadt gefallen.",
      "",
      "Unter Getöteten",
      "waren auch",
      "Bürger von Russland",
      "Dostojewski und Tolstoj\u2026",
      "",
      "In Kyiw",
      "haben russische Raketen",
      "eigene russische Bürger",
      "Bulgakov und Brodski",
      "tödlich getroffen\u2026",
      "",
      "Luftangriffe auf die Ukraine",
      "haben das Bolschoj Theater",
      "und die Russische Akademie der Künste",
      "verpulvert\u2026",
      "",
      "Tschajkowski und Rachmaninow,",
      "Prokofjew und Stravinski",
      "sind davon",
      "für immer und ewig",
      "taub geworden\u2026",
      "",
      "Halyna Petrosanyak.",
      "8.03.2022.",
    ],
  },
  {
    date: "2022/03/01,",
    title: "Halyna Petrosanyak: Aus dem Zyklus \u201ELiebesreigen\u201C",
    titleBorder: true,
    lines: [
      "\u00A012.",
      "\u00A0Rechne nicht",
      "\u00A0mit meiner Zerbrechlichkeit,",
      "\u00A0denn es ist",
      "\u00A0die Brüchigkeit",
      "\u00A0eines Steinbruches.",
      "\u00A0Rechne nicht",
      "\u00A0mit meiner Verletzlichkeit,",
      "\u00A0denn es ist die Verletzlichkeit",
      "\u00A0des Ackers.",
      "\u00A0Verlasse dich nicht",
      "\u00A0auf die Waffe,",
      "\u00A0denn mich verwunden",
      "\u00A0kann nur der,",
      "\u00A0den ich liebe.",
    ],
  },
  {
    date: "30/01/2021, Jens Nielsen",
    title: "Jens Nielsen «Schwund»",
    lines: [
      "",
      "«Wo ist eigentlich",
      "Wo ist hier alles",
      "Diese Strasse",
      "Diese Stadt",
      "Ist das die richtige wo",
      "Fragte ich mich",
      "Und stutzte",
      "",
      "Wie erwacht aus einem",
      "Aber nicht im Bett",
      "Ich stand am Strassenrand",
      "In eleganter Kleidung",
      "Frack",
      "Und tadellose Schuhe",
      "Ich hatte einen Stadtplan in der Hand",
      "Er war ordentlich gefaltet",
      "Aber alt und abgenutzt",
    ],
    footer: "Als wie von jahrelangem»",
  },
];
