import type { JournalContent } from "@/lib/journal-types";

export interface JournalEntry {
  date: string;
  author?: string;
  title?: string;
  titleBorder?: boolean;
  lines: string[];
  images?: { src: string; afterLine: number }[];
  content?: JournalContent;
  footer?: string;
}

export const journalEntries: JournalEntry[] = [
  {
    date: "2022/03/10,",
    title: "Verluste im Krieg",
    lines: [
      "",
      "In Charkiv",
      "vorige Woche",
      "sind vor russischen Bomben",
      "nicht nur Bewohner der Stadt gefallen.",
      "",
      "Unter Getöteten",
      "waren auch",
      "Bürger von Russland",
      "Dostojewski und Tolstoj\u2026",
      "",
      "In Kyiw",
      "haben russische Raketen",
      "eigene russische Bürger",
      "Bulgakov und Brodski",
      "tödlich getroffen\u2026",
      "",
      "Luftangriffe auf die Ukraine",
      "haben das Bolschoj Theater",
      "und die Russische Akademie der Künste",
      "verpulvert\u2026",
      "",
      "Tschajkowski und Rachmaninow,",
      "Prokofjew und Stravinski",
      "sind davon",
      "für immer und ewig",
      "taub geworden\u2026",
      "",
      "Halyna Petrosanyak.",
      "8.03.2022.",
    ],
  },
  {
    date: "2022/03/01,",
    title: "Halyna Petrosanyak: Aus dem Zyklus \u201ELiebesreigen\u201C",
    titleBorder: true,
    lines: [
      "\u00A012.",
      "\u00A0Rechne nicht",
      "\u00A0mit meiner Zerbrechlichkeit,",
      "\u00A0denn es ist",
      "\u00A0die Brüchigkeit",
      "\u00A0eines Steinbruches.",
      "\u00A0Rechne nicht",
      "\u00A0mit meiner Verletzlichkeit,",
      "\u00A0denn es ist die Verletzlichkeit",
      "\u00A0des Ackers.",
      "\u00A0Verlasse dich nicht",
      "\u00A0auf die Waffe,",
      "\u00A0denn mich verwunden",
      "\u00A0kann nur der,",
      "\u00A0den ich liebe.",
      "",
      "Aus dem eben erschienenen Band:\u00A0 \u201EExophonien\u201C",
      "(https://essaisagites.ch/Book/660/Petrosanyak)",
    ],
  },
  {
    date: "30/01/2021, Jens Nielsen",
    title: "Jens Nielsen \u00ABSchwund\u00BB",
    lines: [
      "Das \u00ABZäsur\u00BB-Buch aus der Reihe essais agités (https://essaisagites.ch/Book/368/Die_Z_sur) ist vertont worden. Jens Nielsen gehört mit seinem Text \u00ABSchwund\u00BB zu den Gewinnern der SRF-Ausschreibung \u00ABZehn kurze Geschichten zur langen Pandemie\u00BB. Aus 168 Einsendungen wurden zehn ausgewählt und als Hörspiel produziert. Auf der Website von SRF ist \u00ABSchwund\u00BB nachzuhören (https://bit.ly/3bCVWCe).",
      "",
      "\u00ABWo ist eigentlich",
      "Wo ist hier alles",
      "Diese Strasse",
      "Diese Stadt",
      "Ist das die richtige wo",
      "Fragte ich mich",
      "Und stutzte",
      "Wie erwacht aus einem",
      "Aber nicht im Bett",
      "Ich stand am Strassenrand",
      "In eleganter Kleidung",
      "Frack",
      "Und tadellose Schuhe",
      "Ich hatte einen Stadtplan in der Hand",
      "Er war ordentlich gefaltet",
      "Aber alt und abgenutzt",
    ],
    footer: "Als wie von jahrelangem\u00BB",
  },
  {
    date: "17. Oktober 2020, Michael Stauffer",
    title: "Schwankende Gegenwart\nvon Michael Stauffer",
    lines: [
      "Michael Stauffer hat seinen Beitrag für das \u00ABZäsur\u00BB-Buch (https://essaisagites.ch/Book/368/Die_Z_sur) in Sound rückübersetzt und zusammen mit Wolfgang Zwiauer, Adrien Oggier und Kevin Chesham performt. Hier auf Soundcloud ist er nachzuhören (https://soundcloud.com/life-at-the-zoo/stauffer-oggier-zwiauer-chesham-5-8-20).",
      "",
      "\u00ABMan kann nicht voraussagen, wie sich eine Gesellschaft entwickeln und verändern wird? Man kann nicht dabei zuschauen und dann sagen, aha, deshalb? Es ist immer Zufall, was aus einer Gesellschaft wird, und Glück? Eine Gesellschaft überwindet ihren mentalen Jetlag nie. Die Gesellschaft weiss, ob es reicht, wenn es ihr gut geht mit dem, was sie tut?\u00BB",
    ],
  },
  {
    date: "22. September 2020,",
    lines: [
      "\u00ABMag sein, dass wir uns nach der aktuellen Pandemie \u2013 beziehungsweise nach ihrer ersten Welle \u2013 besser verstehen werden. Was dieses Verstehen uns bringt, ob es uns irgendwo hinbringt, ist noch offen. Bleibt also womöglich nur das reine, folgenlose Begreifen. Es bleibt unser argwöhnischer Blick auf die neu in Gang gesetzten Menschenmassen an Seepromenaden, in Baumärkten und Bahnhöfen, auf Autobahnen. Es bleiben die unaufhaltsame Kraft der Unvernunft, der Wille zum Vergessen, die bedingungslose Hingabe an das Heute. Ja, das Heute gewinnt immer. Das Heute ist der Ort, zu dem alles hinführt \u2013 das Begreifen genauso wie die Taubheit, das Erinnern genauso wie das Vergessen. Einverstanden sein muss man damit nicht. Es zur Kenntnis zu nehmen, ist dennoch nicht das Schlechteste.\u00BB",
      "",
      "Auszug aus: Jens Steiner: Das Heute gewinnt, in: Die Zäsur \u2014 Beobachtungen und Bedenken in Zeiten der Pandemie",
      "",
      "*Von Jens Steiner ist eben erst ein neuer Roman erschienen: \u00ABAmeisen unterm Brennglas\u00BB, Arche Verlag.",
    ],
  },
  {
    date: "29. August 2020, Parwana Amiri",
    title: "Auszug aus: Parwana Amiri: Meine Worte brechen eure Grenzen. Briefe an die Welt aus Moria",
    titleBorder: true,
    lines: [
      "Vierzehnter Brief",
      "",
      "Was würdest du sagen, wenn du statt der Person, die du jetzt bist, eine der über 20\u2019000 obdachlosen Geflüchteten wärst, die im Lager Moria leben, das sich im Winter in eine Hölle und im Sommer in die Wüste Sahara verwandelt?",
      "",
      "Würdest du nicht deine ganze Fassungslosigkeit in die Welt hinausschreien wollen?",
      "",
      "Was würdest du sagen, wenn du dich nach tagelangen Märschen durch Berge, Wälder, Täler und Wüsten, ohne Nahrung und Wasser, in der Kälte, ohne Decken und warme Kleider, aber voller Hoffnung, Europa zu erreichen, plötzlich hinter den Gefängnismauern von Moria wiederfändest, mit deinen zerbrochenen Träumen von Schlaf an einem warmen und sicheren Ort?",
      "",
      "Würdest du nicht deine ganze Fassungslosigkeit in die Welt hinausschreien wollen?",
      "",
      "Was würdest du sagen, wenn du nachts frierend und ängstlich aufwachen, das Schreien deines kranken Kindes hören und deine Hilflosigkeit spüren würdest, weil du ihm nicht helfen kannst? Weil du nur um zwei Euro betteln könntest, um eine Busfahrkarte für die Fahrt ins Krankenhaus zu kaufen, damit sich nach endlosen Stunden des Wartens jemand um dein sterbendes Baby kümmert?",
      "",
      "Würdest du nicht deine ganze Fassungslosigkeit in die Welt hinausschreien wollen?",
      "",
      "(\u2026)",
      "",
      "Und was würdest du sagen, wenn du zuschauen müsstest, wie Mädchen ihre Körper verkaufen? Würdest du nicht auf diese Welt spucken wollen? Was würdest du sagen, wenn du länger als ein Jahr in diesem Gefängnis Moria ausharren müsstest, wobei dein einziges Verbrechen dein Bedürfnis nach Sicherheit und Schutz und dein Wunsch nach diesem kostbaren blauen Stempel* wäre, der dich als Geflüchtete anerkennen würde und deinen Traum wahr werden liesse?",
      "",
      "Würdest du nicht deine ganze Fassungslosigkeit in die Welt hinausschreien wollen?",
      "",
      "Und was würdest du sagen, wenn so einfache Dinge wie eine Heizung und Strom (den du brauchst, um dein Handy aufzuladen, damit du fünf Minuten mit deiner Familie sprechen kannst, die wissen will, ob du noch lebst oder in den Wellen den Tod gefunden hast), eine warme Decke, ein Zuhause, ein Mundvoll Nahrung, eine Tasse Tee zu unerreichbaren Wünschen würden, zu Dingen, die nur in den kühnsten Träumen zu haben wären?",
      "",
      "Würdest du nicht deine ganze Fassungslosigkeit in die Welt hinausschreien wollen?",
      "",
      "Und was würdest du sagen, wenn du eine Handvoll Erde von Morias Grund aufheben und spüren würdest, wie sie schwächer als Asche wird, weil jede Nacht mehr als 20\u2019000 obdachlose Menschen ihre ganze Fassungslosigkeit in die Welt hinausschreien? Nur ein Herz kann ein anderes Herz trösten; die einzige Wärmequelle für ein Herz ist ein anderes Herz.",
      "",
      "Was wirst du also tun? Was wirst du sagen?",
      "",
      "Schreist du deine ganze Fassungslosigkeit in die Welt hinaus?",
    ],
  },
  {
    date: "6. August 2020, Reto Sorg und Michel Mettler",
    title: "Vorwort zur Anthologie \u201EDunkelkammern \u2011 Geschichten vom Erscheinen und Verschwinden\u201C\nBerlin: Suhrkamp 2020",
    lines: [
      "Stoffe sind das, woraus Literatur entsteht. Gestaltlos zuerst, ein blosses Wollen, wachsen sie, werden dringlich und setzen das Schreiben in Gang. Wer Gedrucktes vor sich hat, sieht nur die Enden dieses Wollens. Dem Enden voraus geht meist ein langwieriges Suchen und Kreisen, ein Drehen und Wenden, ermüdend, anstachelnd, aufbauend, ernüchternd, begeisternd.",
      "Die Formlosigkeit des Begriffs Stoff kommt nicht von ungefähr, denn Literatur entsteht ausserhalb von Büchern in wenig linearen Entwicklungen, in den Ankleideräumen, Maulwurfsbauten, Dunkelkammern, Turm- und Nebenzimmern der Imagination. Text: Hervorgegangen aus erwogenen und verworfenen Möglichkeiten, Varianten, Fassungen. Was davon lesbar wird, verbirgt Gespräche, Träume, Lektüren, Reisen und Sprünge, Risse und Schwindel \u2013 das lange Warten und schnelle Zünden, Revision und Zurückkommen. Das Buch und sein Anschein des Fertigen blenden diese Bewegungen aus. Wer einen Roman liest oder ein Gedicht, sieht nicht den Tumult, aus dem sie entstanden sind.",
      "Aktualitätsbezogenes Lesen will zur Kenntnis nehmen, zur Sache kommen, fragt nach Bestimmtem und Bestimmbarem. Diesen Wunsch kann Literatur nur enttäuschen. Sie behandelt keine Themen, sie wälzt Stoffe. Diese erscheinen vorbewusst, näher am Amalgam, dem Schaum, der Brühe. Noch keine Instanz hat sie aufbereitet für den auf eiliges Verständnis drängenden Blick. \u00BBJedes Buch, das gedruckt wurde, ist doch für den Dichter ein Grab oder etwa nicht?\u00AB, bemerkt Robert Walser, als er zunehmend verstreut in Zeitungen und Zeitschriften publiziert. Auch die Stoffe von Friedrich Dürrenmatt unterlaufen die Konvention herkömmlicher Entstehungsgeschichten: \u00BBEnden ist stets willkürlich, ein Aus-der-Hand-Geben, ein Verlieren schliesslich, ein Vergessen, resignierend wie jedes Vergessen. Das noch nicht Geschriebene und das Unvollendete dagegen gehören mir.\u00AB",
      "Da ebenso viele Begriffe vom Stoff existieren, wie es Schreibende gibt, versammelt der vorliegende Band eine bunte Vielfalt an Konzeptionen, Visionen und Chronologien des Entstehens. Siebzehn Originalbeiträge von Autorinnen und Autoren aus der Schweiz zeigen unterschiedliche Arten, wie aus Stoffen Werke werden, Wege, die zwischen Ungeschriebenem und Geschriebenem zurückgelegt werden. Das Interesse an den Tischgottheiten, Privatsalzen und Herdgeistern, die der Entwicklung literarischer Werke Pate stehen, entdeckt eine Dialektik von Verschwinden und Erscheinen, Erleben und Erzählen \u2013 und auch den Umstand, dass fasziniert, was schwer fassbar bleibt. So handeln die hier versammelten Texte von Obsessionen, Bildern und Phänomenen, die nicht zu greifen sind, von denen es aber kein Loskommen gibt, bis sie Form angenommen haben. Aus solcher Unruhe geht die Vielheit an Tonlagen und Schreibweisen dieses Bandes hervor, der neue und bewährte literarische Stimmen durcheinander klingen lässt.",
      "Das Interesse an der Stofflichkeit von Literatur, an den Quellen und Reizbarkeiten, aus denen sie entspringt, steht quer zu den ökonomischen und medialen Realitäten des Literaturbetriebs \u2013 und verbindet doch alle involvierten Akteure. Von Literatur handeln, heisst, ihre Verfasstheit, ihre Hintergründe und Bedingungen reflektieren. Dazu lädt diese Sammlung ein, für einmal nicht mittels Essays oder Gesprächen, sondern in Form von Erzählungen.",
      "Michel Mettler und Reto Sorg",
    ],
  },
  {
    date: "13. Juli 2020, Elisabeth Wandeler-Deck",
    lines: [
      "Margret Kreidl, Wien, schenkte mir eines aus ihrer Serie von Akrosticha, die immer über das Wort \u00ABGedicht\u00BB gebaut sind. Auf dem pdf dann der handschriftliche Hinweis \u00ABHier hätte noch ein Schulterakrostichon Platz\u00BB \u2013 wir hatten einander von unserer je wehen Schulter berichtet. Ich versuchte also ein Schulterakrostichon für Margret Kreidl, gefolgt von einem eigenen Gedichtakrostichon.",
      "",
      "02./06./07./08.05.2019; 07.07.2020",
      "",
      "silbe senf sammle häutchen zaus. samt kein.",
      "catering sämtlich jemanden schlitzohrig rau",
      "hummle ein. etwas jemandem. sie. abgekartet.",
      "umsonst umgrade fragezeichen. etwas es saus.",
      "lausch. wimpere wimmern im fleisch zu. viel",
      "turmaus. je jemander. sieh. sst. schrapp nelk au weh",
      "er oder was bist du gradsaus. haus. ausser.",
      "rrrrrrr. serifenwehen schon besser so. frass milben.",
      "",
      "gestimmte quasi gern einzig",
      "egal",
      "da dort drum mit",
      "innigster empfindung",
      "casting noch heute der schönste",
      "husch",
      "take gelungen takt tal die träger betasten",
    ],
  },
  {
    date: "Gottlieben, 2. Mai 2019, Annette Hug",
    title: "Trobairitz \u2013 eine Heldin?",
    lines: [
      "Der Titel des Projekts war schnell klar: \u00ABTrobadora\u00BB steht im Titel des Romans, um den es geht. Weil die Figuren selbst viel über Literatur nachdenken, nennen sie das Buch, in dem sie vorkommen, einen \u00ABoperativen Montageroman\u00BB. Ich war der Meinung, dass er viel enthält, was irgendwie weitergehen könnte. Deshalb heisst das Projekt \u00ABtrobadora.montage\u00BB.",
      "",
      "Geschenk einer Leserin: Taschenbuchausgabe im Luchterhand-Verlag mit eingelegtem Zeitungsartikel.",
      "",
      "Auf dem Weg zu einer Lesung in Gottlieben waren Johanna Lier und ich mit dem fahrbaren Requisitenkasten und Stehpult unterwegs. Ein kleines Mädchen las die Beschriftung und fragte: \u00ABWas ist eine Trobadora?\u00BB Johanna erzählte von Frauen, die im Mittelalter Lieder vorsangen. Ich glaube, sie sagte auch, dass diese Frauen Männer besangen, die sie besonders schön fanden. Auf der Heimfahrt, kurz vor Mitternacht, wollten dann mehrere Männer wissen, was eine Trobadora sei. Sie fragten auf Englisch, Spanisch oder Deutsch. Auch das Publikum in Gottlieben war gesprächig. Wir diskutierten zum Beispiel über den Epos und die Frage, ob Heldinnen und Helden, die ihre Gesellschaft verbessern wollen, in der Literatur überhaupt noch denkbar sind.",
      "",
      "Johanna Lier, auf dem Weg an die Lesung im Literaturhaus Gottlieben, am 2. Mai 2019.",
      "",
      "Drei Frauen hatten ihre Morgner-Ausgaben zur Lesung mitgebracht. Da war eine Erstausgabe im Aufbau-Verlag, 1974, und zwei Ausgaben aus dem Luchterhand-Verlag. Ich verstand nicht recht, weshalb mir eine der Frauen ihr Exemplar unbedingt schenken wollte. War sie überzeugt, dass sie das Buch nie mehr anschauen würde, wollte es aber irgendwo aufgehoben wissen? Jedenfalls nahm ich das Buch dankend an und fand darin einen Zeitungsartikel: \u00ABWeibliche Troubadoure\u00BB. Es ist die Besprechung einer Ausstellung aus dem Jahr 1983 im Landesmuseum Hannover. Der Artikel enthielt Hinweise, die ich verfolgen wollte, und so wurde mir deutlich, wie viel seit dem ersten Erscheinen von Irmtraud Morgners Roman geforscht worden ist. Zum Beispiel haben Forscherinnen der Hochschule für Musik und Theater in Hamburg die Webseite \u00ABSpielfrauen des Mittelalters\u00BB erarbeitet. Da findet sich auch die historische Gestalt Beatriz de Dia, die hinter der Titelfigur von Morgners \u00ABLeben und Abenteuer der Trobadora Beatriz nach Zeugnissen ihrer Spielfrau Laura\u00BB steht. Zu meiner Überraschung lernte ich auch, dass der Beruf der Minnesängerin auf Deutsch eigentlich Trobairitz heisst.",
    ],
    images: [
      { src: "/journal/trobadora-buch.png", afterLine: 2 },
      { src: "/journal/trobadora-lesung.png", afterLine: 5 },
    ],
  },
  {
    date: "Mai und Juni 2019, Annette Hug",
    title: "Kein Kanon? Die Kanon? Unser Kanon?",
    lines: [
      "\u00ABJe verwirrender die Welt scheint, um so stärker wird dem Menschen die Sehnsucht nach einer Ordnung. Nach einer Einordnung. Nach anderen Menschen, die ihm Ideen, Anregung und Halt geben. Die ihm Leuchtturm sein können, in der immer wiederkehrenden, scheinbar schrecklichsten aller Zeiten\u00BB, schreibt Sibylle Berg im Vorwort der Seite diekanon.org. Immer neue Listen und Register berühmter Männer haben uns nicht gerettet, stellt sie fest. Es müssen neue Listen her. Mit weiteren Autorinnen arbeitet sie an einem Kanon wichtiger Frauen in Literatur, Kunst, Musik und Wissenschaft.",
      "",
      "\u00ABDer literarische Kanon. Ein Abgesang\u00BB, hiess dagegen eine Aktion von Autorinnen am Frauenstreik vom 14. Juni 2019. Das Stehpult des Trobadora-Projekts, das auch eine rollende Kiste ist, spielte bei dieser Aktion eine Nebenrolle. Wir trugen eine Bestenliste aus der Zeitung \u00ABLe Monde\u00BB vor: die Männernamen im Kanon, die Frauennamen im Gleichklang. \u00ABMarguerite Duras\u00BB und \u00ABNathalie Sarraute\u00BB ragten aus einem kakophonischen Meer von Männernamen auf. Um nicht in diesem Meer zu versinken, lasen wir danach kurze Passagen von Lieblingsautorinnen vor. Da wir kaum geprobt hatten und spontan ein Schluss für den Kanon gefunden werden musste, tauchte plötzlich ein Slogan der Klimademos auf, leicht abgewandelt: \u00ABWem sin Kanon? Oise Kanon!\u00BB",
      "",
      "Das passte aber nicht zum Titel, also skandierten wir: \u00ABWem sin Kanon? Kein Kanon!\u00BB",
      "",
      "\u00ABOise Kanon\u00BB hätte gut zur Webseite diekanon.org gepasst. Die Gruppe, die sich an einem Stammtisch der Autorinnengruppe RAUF getroffen hatte, um die Aktion am Frauenstreik vorzubereiten, war aber folgender Meinung: Es ist weder realistisch noch wünschbar, dass sich die literarische Öffentlichkeit auf einen Korpus der relevantesten Werke einigt. Die wenigsten von uns sind nur in einer Sprache zu Hause. Wir lesen in mehreren Sprachen und können in keiner einzigen den vollen Überblick behalten. Mit empfindlichen Lücken ist immer zu rechnen. Ausserdem wackelt die klare Abgrenzung von U- und E-Literatur zu Recht. In der realen Welt der Bücher müssen wir uns immer wieder neu darüber verständigen, was relevant ist, was anregt, weiterführt oder produktiv irritiert. Fixe Listen geben eine Ordnung vor, die kaum mehr relevant ist.",
      "",
      "Aktion \u00ABDer literarische Kanon. Ein Abgesang\u00BB am Frauenstreik vom 14. Juni 2019, Stadelhoferplatz Zürich.",
      "",
      "An der Vorbereitungssitzung der Buchhändlerinnen der Gewerkschaft syndicom, die gemeinsam mit den Autorinnen am Frauenstreik protestierten \u2013 und bei Orell Füssli eine Protestpause einlegten \u2013, wurde aber deutlich, dass durchaus Ordnungen existieren und zwar ganz materiell: Regale mit unterschiedlichen Beschriftungen. \u00ABKlassiker\u00BB, \u00ABUnterhaltung\u00BB, \u00ABBeststeller\u00BB. Vielleicht sogar \u00ABFrauenliteratur\u00BB. Die Buchhändlerinnen, die am Frauenstreik protestierten, würden gern anders einordnen als vorgegeben. Wenn es nach ihnen ginge, würden in den Regalen mehr Titel von Autorinnen stehen. In den Regalen und Auslagen der Buchhandlungen verwandelt sich die Sehnsucht nach Leuchttürmen, von der Sibylle Berg schreibt, in eine harte ökonomische Ordnung.",
      "",
      "An die Verwirrung, der diese Sehnsucht entspringt, erinnerten dieses Jahr die Jurydiskussionen des Bachmannpreises. In Klagenfurt wurde deutlich, dass bei zentralen Fragen der Literaturkritik gemeinsame Begriffe und Referenzen fehlen. Zum Beispiel wenn es darum geht, zu benennen, was gute Literatur in der Auseinandersetzung mit dem Nationalsozialismus kann oder soll. Als die Jury darüber sprach, konnte ich mich selbst bei einer inneren Kehrtwende beobachten. Hatte ich in der Vorbereitung des Frauenstreiks noch die Position \u00ABKein Kanon!\u00BB unterstützt, wollte ich nun ausrufen: \u00ABHinter Ilse Aichinger, Ruth Klüger und Paul Celan kann man doch nicht zurückgehen!\u00BB",
      "",
      "Wohin diese Gedanken führen, ist mir noch nicht klar. Geht es darum, die Machtfrage offen zu stellen und zu sagen, dass \u00ABwir\u00BB \u2013 wer immer wir genau sind \u2013 den Kanon neu festlegen wollen? Sibylle Berg scheint dafür zu plädieren, wenn sie \u00ABdie Kanon\u00BB wie folgt beschreibt: \u00ABNeue Namen mit Ideen und der Kompetenz, die vielleicht etwas zu einem freundlicheren Miteinander in der Welt beitragen können.\u00BB Oder gewinnt die Literatur \u2013 und die Freundlichkeit \u2013, wenn sich die Listen generell verflüssigen und Autoritäten wackeln? War vielleicht der musikalische Zugang der beste? Der Kanon ist ein Genre unter vielen und es wird immer viele davon geben: Längere, kürzere, schönere, traurige, dumme und kluge. Schon wollte ich schreiben: Und jede singt dann ihren Lieblingskanon. Aber mindestens vier Stimmen müssen sich schon finden, sonst wird das nichts.",
    ],
    images: [
      { src: "/journal/kanon-aktion.png", afterLine: 8 },
    ],
  },
];
